doctrine:
    dbal:
        default_connection: mysql
        connections:
            cover:
                driver: oci8
                host: '%env(resolve:ORACLE_HOST)%'
                port: '%env(resolve:ORACLE_PORT)%'
                dbname: '%env(resolve:ORACLE_SID)%'
                user: '%env(resolve:ORACLE_USER)%'
                password: '%env(resolve:ORACLE_PASSWORD)%'
                charset: AL32UTF8

            mysql:
                driver: pdo_mysql
                server_version: '8.0'
                host: '%env(resolve:MYSQL_HOST)%'
                port: '%env(resolve:MYSQL_PORT)%'
                dbname: '%env(resolve:MYSQL_DB)%'
                user: '%env(resolve:MYSQL_USER)%'
                password: '%env(resolve:MYSQL_PASSWORD)%'
                charset: utf8mb4

    orm:
        default_entity_manager: mysql
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true


        entity_managers:
            cover:
                connection: cover
                second_level_cache:
                    enabled: false
                mappings:
                    Cover:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Cover'
                        prefix: 'App\Entity\Cover'
                        alias: Cover

            mysql:
                connection: mysql
                mappings:
                    Mysql:
                        is_bundle: false
                        type: attribute
                        dir: '%kernel.project_dir%/src/Entity/Mysql'
                        prefix: 'App\Entity\Mysql'
                        alias: Mysql
